### ISSUE TITLE
Accepting xcode eula needs manual user input

### ISSUE THREAD

**Issue by tibuntu** [monta92/OSX-Tools-Set-Up-Automation-Project#1]
https://github.com/monta92/OSX-Tools-Set-Up-Automation-Project/blob/5fd97ac36c8d9aa44240a5bd4e0b3d0d61775107/bin/bootstrap.sh#L21
https://github.com/monta92/OSX-Tools-Set-Up-Automation-Project/blob/5fd97ac36c8d9aa44240a5bd4e0b3d0d61775107/bin/bootstrap.sh#L22
https://github.com/monta92/OSX-Tools-Set-Up-Automation-Project/blob/5fd97ac36c8d9aa44240a5bd4e0b3d0d61775107/bin/bootstrap.sh#L23

`sudo xcodebuild -license accept`

Not sure if it still works :)

**Comment by monta92** [comment]
Will check that and modify the script along ;).
Any suggestion of useful utilities will be more than welcome.
